name: Measure coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
